### ISSUE TITLE
Foxy/Rolling Release

### ISSUE THREAD

**Issue by DLu** [samsung-ros/ament_download#2]
Any reason to not include a foxy/rolling release?

**Comment by SteveMacenski** [comment]
Frankly, I haven't used it recently, this was created in the early days of ROS 2 before binaries were even available to grab resources we needed.

If this is of use to you currently, I can do a release if that would be helpful?

**Comment by DLu** [comment]
I was trying to figure out a replacement for `catkin_download_test_data` so I ended up here. Not sure if there's something better.

**Comment by SteveMacenski** [comment]
I'm not sure either

**Comment by charlielito** [comment]
I am also looking for a replacement for `catkin_download_test_data`. Could this be included in recent ros2 releases?

**Comment by SteveMacenski** [comment]
Try it out and let me know if it meets you needs, if so, happy to run a release again. I built this honestly such a long time ago and I haven't thought about it much since then. It was supposed to be the first cmake tool of many but I got side tracked when I had to take over the Nav2 project. Almost all the code was taken from `catkin_download` as I mention in the readme file so it should be a good option

**Comment by charlielito** [comment]
Just tried it and it works as expected

**Comment by SteveMacenski** [comment]
I'll add a release to my queue this week :smile:

**Comment by SteveMacenski** [comment]
Or actually, I'll just do it now
- Humble https://github.com/ros/rosdistro/pull/33655 
- Foxy https://github.com/ros/rosdistro/pull/33657
- Rolling  https://github.com/ros/rosdistro/pull/33656
